version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@eslint-community/*"
          - "@typescript-eslint/*"
      react-packages:
        patterns:
          - "react*"
      electron-fuses-packages:
        patterns:
          - "@electron-forge/plugin-fuses"
          - "@electron/fuses"
