version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
      react-packages:
        patterns:
          - "react*"
