import path from 'path';
import os from 'os';
import {
  app,
  BrowserWindow,
  ipcMain,
  shell,
  nativeTheme,
  dialog,
  Notification,
} from 'electron';
import { AzureDevOpsService } from './infrastructure/azure/azureDevOpsService';
import { AzureDevOpsCodeReviewService } from './infrastructure/azure/azureDevOpsCodeReviewService';
import { GitHubService } from './infrastructure/github/gitHubService';
import { GitHubCodeReviewService } from './infrastructure/github/gitHubCodeReviewService';
import { CopilotService } from './infrastructure/copilot/copilotService';
import { ConfluenceService } from './infrastructure/confluence/confluenceService';
import { AppSettings } from '../types';
import { IssueTrackerProvider } from './infrastructure/providers/IssueTrackerProvider';
import { DocumentationProvider } from './infrastructure/providers/DocumentationProvider';
import { CodeReviewProvider } from './infrastructure/providers/CodeReviewProvider';
import { StoryWriterService } from './features/story-writer/storyWriterService';
import { TestCaseWriterService } from './features/test-case-writer/testCaseWriterService';
import { StoryElaboratorService } from './features/story-elaborator/storyElaboratorService';
import { PromptComplexityService } from './features/settings/promptComplexityService';
import { GitService } from './infrastructure/git/gitService';
import { PRReviewerService } from './features/pr-reviewer/prReviewerService';
import {
  decryptSettings,
  encryptSettings,
  migrateStoredSettings,
} from './infrastructure/settingsSecureStorage';

// Initialize auto-updates
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('update-electron-app').updateElectronApp();

// Disable security warnings in development mode to keep the developer console clean.
// In production (app.isPackaged === true), warnings remain active.
if (!app.isPackaged) {
  process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = 'true';
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Global store instance to be initialized dynamically
// Disabling eslint no-explicit-any because we're dynamically importing ElectronStore.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let store: any;

// Initialization helper for ESM dependencies in CJS
async function initStore() {
  if (!store) {
    const Store = (await import('electron-store')).default;
    store = new Store();
  }
  return store;
}

// Global service instances
let issueTrackerService: IssueTrackerProvider | null = null;
let confluenceService: DocumentationProvider | null = null;
let codeReviewService: CodeReviewProvider | null = null;
const copilotService = new CopilotService();
const gitService = new GitService();
const storyWriterService = new StoryWriterService(copilotService);
const testCaseWriterService = new TestCaseWriterService(copilotService);
const storyElaboratorService = new StoryElaboratorService(
  copilotService,
  gitService,
  async () => {
    try {
      return await getConfluenceService();
    } catch {
      return null;
    }
  },
);
const promptComplexityService = new PromptComplexityService(copilotService);
const prReviewerService = new PRReviewerService(
  gitService,
  copilotService,
  async () => {
    try {
      return await getIssueTrackerService();
    } catch {
      return null;
    }
  },
  async () => {
    try {
      return await getConfluenceService();
    } catch {
      return null;
    }
  },
  async () => {
    try {
      return await getCodeReviewProvider();
    } catch {
      return null;
    }
  },
);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

async function getDecryptedSettings(): Promise<AppSettings> {
  const s = await initStore();
  const rawSettings = (s.get('settings') ?? {}) as AppSettings;
  return decryptSettings(rawSettings);
}

async function saveEncryptedSettings(settings: AppSettings): Promise<void> {
  const s = await initStore();
  const encrypted = encryptSettings(settings);
  s.set('settings', encrypted);
}

// IPC Handlers
ipcMain.handle('get-settings', async () => {
  return getDecryptedSettings();
});

ipcMain.handle('get-version-status', async () => {
  const s = await initStore();
  const lastRunVersion = s.get('lastRunVersion') as string | undefined;
  const currentVersion = app.getVersion();

  const isUpdated = !lastRunVersion || lastRunVersion !== currentVersion;

  if (isUpdated) {
    s.set('lastRunVersion', currentVersion);
  }

  return {
    isUpdated,
    previousVersion: lastRunVersion,
    currentVersion,
  };
});

ipcMain.handle('open-external', async (event, url: string) => {
  return shell.openExternal(url);
});

/* eslint-disable @typescript-eslint/no-explicit-any */
function trimProperties(obj: any): any {
  if (obj === null || obj === undefined) return obj;
  if (typeof obj === 'string') return obj.trim();
  if (typeof obj === 'object') {
    const out: any = Array.isArray(obj) ? [] : {};
    for (const key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        out[key] = trimProperties(obj[key]);
      }
    }
    return out;
  }
  return obj;
}
/* eslint-enable @typescript-eslint/no-explicit-any */

ipcMain.handle('save-settings', async (event, settings: AppSettings) => {
  // Trim and normalize saved settings to avoid whitespace-caused auth issues
  const sanitizedSettings = trimProperties(settings) as AppSettings;

  await saveEncryptedSettings(sanitizedSettings);

  copilotService.setModel(sanitizedSettings.copilotModel || 'auto');
  copilotService.clearCache(sanitizedSettings.copilotToken);

  // Apply theme immediately
  const theme = sanitizedSettings.theme ?? 'auto';
  nativeTheme.themeSource = theme === 'auto' ? 'system' : theme;

  // Invalidate services so they get re-created on the next fetch with new credentials
  issueTrackerService = null;
  confluenceService = null;
  codeReviewService = null;

  return { success: true };
});

async function getCodeReviewProvider(): Promise<CodeReviewProvider> {
  if (!codeReviewService) {
    const settings = await getDecryptedSettings();
    const sanitized = trimProperties(settings) as AppSettings;
    const source = sanitized.sources?.code || 'azureDevOps';

    if (source === 'github') {
      const githubConn = sanitized.connectors?.github;
      const token = githubConn?.token;
      const defaultOwner = githubConn?.owner || '';
      if (!token) {
        throw new Error('GitHub settings token is missing.');
      }
      codeReviewService = new GitHubCodeReviewService(token, defaultOwner);
    } else {
      const azureConn = sanitized.connectors?.azureDevOps;
      const org = azureConn?.org;
      const pat = azureConn?.pat;
      const project = azureConn?.project;
      if (!org || !pat) {
        throw new Error('Azure DevOps settings are missing.');
      }
      codeReviewService = new AzureDevOpsCodeReviewService(
        org,
        pat,
        project || '',
      );
    }
  }
  return codeReviewService;
}

async function getIssueTrackerService(): Promise<IssueTrackerProvider> {
  if (!issueTrackerService) {
    const settings = await getDecryptedSettings();
    const sanitized = trimProperties(settings) as AppSettings;
    const source = sanitized.sources?.issues || 'azureDevOps';

    if (source === 'github') {
      const githubConn = sanitized.connectors?.github;
      const token = githubConn?.token;
      const defaultOwner = githubConn?.owner || '';
      if (!token) {
        throw new Error('GitHub settings token is missing.');
      }
      issueTrackerService = new GitHubService(token, defaultOwner);
    } else {
      const azureConn = sanitized.connectors?.azureDevOps;
      const org = azureConn?.org;
      const pat = azureConn?.pat;
      if (!org || !pat) {
        throw new Error('Azure DevOps settings are missing.');
      }
      issueTrackerService = new AzureDevOpsService(org, pat);
    }
  }
  return issueTrackerService;
}

ipcMain.handle('fetch-ticket', async (event, ticketId) => {
  const service = await getIssueTrackerService();
  return service.fetchTicket(ticketId);
});

ipcMain.handle('search-tickets', async (event, query, type) => {
  const service = await getIssueTrackerService();
  return service.searchTickets(query, type);
});

ipcMain.handle(
  'get-azure-work-item-types',
  async (event, org, pat, project) => {
    const service = new AzureDevOpsService(org, pat);
    return service.getWorkItemTypes(project);
  },
);

ipcMain.handle(
  'generate-test-cases',
  async (event, ticketData, additionalContext, modelOverride) => {
    const settings = await getDecryptedSettings();
    return testCaseWriterService.generateTestCases(
      ticketData,
      additionalContext,
      modelOverride,
      settings,
      (line: string) => {
        event.sender.send('test-case-line', line);
      },
    );
  },
);

async function getConfluenceService(): Promise<DocumentationProvider> {
  if (!confluenceService) {
    const settings = await getDecryptedSettings();
    const sanitized = trimProperties(settings) as AppSettings;
    const atlassianConn = sanitized.connectors?.atlassian;
    const url = atlassianConn?.url;
    const user = atlassianConn?.username;
    const token = atlassianConn?.token;

    if (!url || !token) {
      throw new Error('Confluence URL and Token are required.');
    }

    confluenceService = new ConfluenceService(url, user || '', token);
  }
  return confluenceService;
}

ipcMain.handle('fetch-confluence-page', async (event, pageId) => {
  const service = await getConfluenceService();
  return service.fetchPage(pageId);
});

ipcMain.handle('search-confluence-pages', async (event, query) => {
  const service = await getConfluenceService();
  return service.searchPages(query);
});

ipcMain.handle(
  'generate-stories',
  async (event, pageData, additionalContext, modelOverride) => {
    const settings = await getDecryptedSettings();
    return storyWriterService.generateStories(
      pageData,
      additionalContext,
      modelOverride,
      settings,
      (line: string) => {
        event.sender.send('story-line', line);
      },
    );
  },
);

ipcMain.handle('check-copilot-auth', async () => {
  const settings = await getDecryptedSettings();
  return copilotService.checkAuthStatus(settings.copilotToken);
});

ipcMain.handle('check-environment', async () => {
  return copilotService.checkEnvironment();
});

ipcMain.handle('install-copilot-cli', async () => {
  return copilotService.installCopilotCli();
});

ipcMain.handle('list-copilot-models', async () => {
  const settings = await getDecryptedSettings();
  return copilotService.listModels(settings.copilotToken);
});

ipcMain.handle('check-prompt-complexity', async (event, type, prompts) => {
  const settings = await getDecryptedSettings();
  return promptComplexityService.checkPromptComplexity(type, prompts, settings);
});

ipcMain.handle('select-directory', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
  });
  if (result.canceled) {
    return null;
  }
  return result.filePaths[0];
});

ipcMain.handle(
  'start-story-elaboration',
  async (
    event,
    ticketData,
    repoPath,
    additionalContext,
    modelOverride,
    branch,
  ) => {
    const settings = await getDecryptedSettings();
    return storyElaboratorService.startStoryElaboration(
      ticketData,
      repoPath,
      additionalContext,
      modelOverride,
      settings,
      branch,
      (line: string) => {
        event.sender.send('elaboration-line', line);
      },
    );
  },
);

ipcMain.handle('send-elaboration-answer', async (event, ticketId, answer) => {
  return storyElaboratorService.sendElaborationAnswer(
    ticketId,
    answer,
    (line: string) => {
      event.sender.send('elaboration-line', line);
    },
  );
});

ipcMain.handle('stop-story-elaboration', async (event, ticketId) => {
  return storyElaboratorService.stopStoryElaboration(ticketId);
});

ipcMain.handle(
  'pr-reviewer:get-details',
  async (event, repoPath, prUrlOrId) => {
    const settings = await getDecryptedSettings();
    return prReviewerService.getPRDetails(repoPath, prUrlOrId, settings);
  },
);

ipcMain.handle(
  'pr-reviewer:checkout',
  async (event, repoPath, prNumber, expectedRepoName) => {
    const settings = await getDecryptedSettings();
    return prReviewerService.checkoutAndDiff(
      repoPath,
      prNumber,
      expectedRepoName,
      settings,
    );
  },
);

ipcMain.handle(
  'pr-reviewer:get-diff-files',
  async (event, repoPath, targetBranch) => {
    const effectivePath = prReviewerService.getEffectiveRepoPath(repoPath);
    return gitService.getDiffFiles(effectivePath, targetBranch);
  },
);

ipcMain.handle(
  'pr-reviewer:get-file-diff',
  async (event, repoPath, targetBranch, filePath) => {
    const effectivePath = prReviewerService.getEffectiveRepoPath(repoPath);
    return gitService.getFileDiff(effectivePath, targetBranch, filePath);
  },
);

ipcMain.handle('pr-reviewer:search-prs', async (event, searchType) => {
  const settings = await getDecryptedSettings();
  return prReviewerService.getProjectPRs(searchType, settings);
});

ipcMain.handle('pr-reviewer:get-phases', async () => {
  return prReviewerService.loadPhasesFromDisk();
});

ipcMain.handle('pr-reviewer:open-directory', async () => {
  const homeDir = os.homedir();
  const dirPath = path.join(homeDir, '.stitch', 'pr-reviewer');
  try {
    await shell.openPath(dirPath);
    return true;
  } catch (err) {
    console.error(`Failed to open directory ${dirPath}:`, err);
    return false;
  }
});

ipcMain.handle(
  'pr-reviewer:check-worktrees',
  async (event, baseDir: string) => {
    return prReviewerService.checkWorktrees(baseDir);
  },
);

ipcMain.handle(
  'pr-reviewer:clean-worktrees',
  async (event, baseDir: string) => {
    return prReviewerService.cleanWorktrees(baseDir);
  },
);

ipcMain.handle('get-cpu-count', () => {
  return os.cpus().length;
});

ipcMain.handle(
  'pr-reviewer:review',
  async (
    event,
    repoPath,
    targetBranch,
    customInstructions,
    modelOverride,
    enabledPhaseIds,
    prDescription,
    prId,
    maxParallelism,
    persona,
  ) => {
    const settings = await getDecryptedSettings();
    return prReviewerService.reviewPR(repoPath, targetBranch, settings, {
      modelOverride,
      customInstructions,
      enabledPhaseIds,
      prDescription,
      prId,
      maxParallelism,
      persona,
      onLine: (line: string) => {
        event.sender.send('pr-reviewer:review-line', line);
      },
    });
  },
);

ipcMain.handle(
  'pr-reviewer:post-comment',
  async (event, repoPath, prUrlOrId, comment) => {
    const settings = await getDecryptedSettings();
    return prReviewerService.postPRComment(
      repoPath,
      prUrlOrId,
      comment,
      settings,
    );
  },
);

ipcMain.handle(
  'pr-reviewer:critique-comments',
  async (event, comments, prDescription, modelOverride) => {
    const settings = await getDecryptedSettings();
    return prReviewerService.critiqueComments(comments, settings, {
      modelOverride,
      prDescription,
    });
  },
);

ipcMain.handle('pr-reviewer:get-repo-path-history', async (event, repoName) => {
  const s = await initStore();
  return s.get(`repo-paths.${repoName}`) || null;
});

ipcMain.handle(
  'pr-reviewer:save-repo-path-history',
  async (event, repoName, repoPath) => {
    const s = await initStore();
    s.set(`repo-paths.${repoName}`, repoPath);
    return true;
  },
);

ipcMain.handle('pr-reviewer:get-author-persona', async (event, authorKey) => {
  const s = await initStore();
  const safeKey = encodeURIComponent(authorKey).replace(/\./g, '%2E');
  return s.get(`author-personas.${safeKey}`) || null;
});

ipcMain.handle(
  'pr-reviewer:save-author-persona',
  async (event, authorKey, personaName) => {
    const s = await initStore();
    const safeKey = encodeURIComponent(authorKey).replace(/\./g, '%2E');
    if (personaName && personaName !== 'None') {
      s.set(`author-personas.${safeKey}`, personaName);
    } else {
      s.delete(`author-personas.${safeKey}`);
    }
  },
);

ipcMain.handle(
  'pr-reviewer:verify-repo-path',
  async (event, repoPath: string) => {
    const isGitRepo = await gitService.checkGitRepo(repoPath);
    if (!isGitRepo) {
      return {
        isGitRepo: false,
        path: repoPath,
        originalPath: repoPath,
        wasModified: false,
      };
    }

    const rootPath = await gitService.getRepoRoot(repoPath);
    if (!rootPath) {
      return {
        isGitRepo: false,
        path: repoPath,
        originalPath: repoPath,
        wasModified: false,
      };
    }

    const normSelected = path.resolve(repoPath);
    const normRoot = path.resolve(rootPath);

    const isSame =
      process.platform === 'win32' || process.platform === 'darwin'
        ? normSelected.toLowerCase() === normRoot.toLowerCase()
        : normSelected === normRoot;

    return {
      isGitRepo: true,
      path: rootPath,
      originalPath: repoPath,
      wasModified: !isSame,
    };
  },
);

ipcMain.handle('add-comment', async (event, ticketId, text, options) => {
  const service = await getIssueTrackerService();
  return service.addComment(ticketId, text, options);
});

ipcMain.handle(
  'create-ticket',
  async (event, type, parentTicketId, data, options) => {
    const service = await getIssueTrackerService();
    return service.createTicket(type, parentTicketId, data, options);
  },
);

// Keep active notifications in memory to prevent garbage collection before click/close events fire
const activeNotifications = new Set<Notification>();

ipcMain.handle('show-notification', (event, title: string, body: string) => {
  const webContents = event.sender;
  const win = BrowserWindow.fromWebContents(webContents);
  if (Notification.isSupported()) {
    try {
      const notification = new Notification({
        title,
        body,
      });

      activeNotifications.add(notification);

      notification.on('click', () => {
        if (win) {
          if (win.isMinimized()) {
            win.restore();
          }
          win.show();
          win.focus();
        }
        activeNotifications.delete(notification);
      });

      notification.on('close', () => {
        activeNotifications.delete(notification);
      });

      notification.show();
    } catch (err) {
      console.error('Failed to show notification:', err);
    }
  } else {
    console.warn('Native notifications are not supported on this platform.');
  }
});

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 890,
    width: 1200,
    titleBarStyle: 'hidden',
    titleBarOverlay:
      process.platform === 'win32'
        ? {
            color: '#133865',
            symbolColor: '#ffffff',
            height: 44,
          }
        : false,
    trafficLightPosition: { x: 15, y: 15 }, // Adjusted for 44px height
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Prevent default reload hotkeys (Cmd/Ctrl+R, Cmd/Ctrl+Shift+R)
  mainWindow.webContents.on('before-input-event', (event, input) => {
    const isControlOrMeta =
      process.platform === 'darwin' ? input.meta : input.control;
    if (isControlOrMeta && input.key.toLowerCase() === 'r') {
      event.preventDefault();
    }
  });

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  if (process.platform === 'win32') {
    app.setAppUserModelId('com.squirrel.stitch.Stitch');
  }

  const s = await initStore();

  // Migrate any existing plain text credentials to secure storage
  await migrateStoredSettings(s);

  const settings = await getDecryptedSettings();
  const theme = settings.theme ?? 'auto';
  nativeTheme.themeSource = theme === 'auto' ? 'system' : theme;

  copilotService.setModel(settings.copilotModel || 'auto');
  copilotService.initializeAsync(settings.copilotToken).catch((err) => {
    console.error('Failed to initialize copilotService on startup:', err);
  });

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

app.on('will-quit', async () => {
  await storyElaboratorService.cleanup();
});
